### ISSUE TITLE
Possible capping of API calls

### ISSUE THREAD

**Issue by aronkahrs-us** [gustavoqzdaa/ute_energy#10]
This morning I tried to check the energy consumption and to my surprise the integration wasn't working, I tried to reload it and still it was not working so i checked the logs and found this:
- `('Send reading request return status: 429, reason: Too Many Requests, content: API calls quota exceeded! maximum admitted 10 per 1d.',)`
- `('Send reading request return status: 429, reason: Too Many Requests, content: API calls quota exceeded! maximum admitted 2 per 5m.',)`
- `('Login return status: 429, reason: Too Many Requests, content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>429 Too Many Requests</title>\n</head><body>\n<h1>Too Many Requests</h1>\n<p>The user has sent too many requests\nin a given amount of time.</p>\n</body></html>\n',)`

Apparently now there is a limit of 2 calls per 5 minutes and 10 calls per day or at least thats what the error says, so this potentially breaks the integration.

**Comment by lucianolacurcia** [comment]
Fortunately, it seems that they added this rate limit only on certain endpoints, for example I am getting this error with `latest_month_charges` and `latest_month_consumption` but not with `Ute Energy Power` and `Ute Energy Current`. 

Maybe we should limit the request to this sensors that are not changing much normally.

**Comment by rogsme** [comment]
Hey! I also have a [HomeAssistant integration](https://github.com/rogsme/ute_homeassistant_integration), but yours looks way better. I'm okay with deprecating mine in favor of yours, if that's okay with you.

I made [my own PyPi package](https://pypi.org/project/ute-wrapper/) to reverse engineer the UTE Android App. I found that the rate limiting happens on the `/lastReading/30` endpoint, which is the one that gets the current power usage. How are you planning to go around that?

Also, a side note: You don't need the SMS response to login to the UTE API. Only the phone number and email works, you can check my pypi package and test if you want 😄
