### ISSUE TITLE
API calls quota exceeded!

### ISSUE THREAD

**Issue by eroldan** [gustavoqzdaa/ute_energy#12]
I don't know when or why it broke. I'm getting this
![image](https://github.com/user-attachments/assets/7500d83d-be7e-4d07-b1ff-388575539563)

**Comment by gastonmorixe** [comment]
try changing the polling rate from 10 minutes to at least 15 minutes since the UTE API's max rate is ~140/day 

https://github.com/gustavoqzdaa/ute_energy/blob/db853b243001bc17b93eed155997827d66b0a16d/custom_components/ute_energy/const.py#L89

**Comment by eroldan** [comment]
The error message says: API calls quota exceeded! maximum admitted 2 per 5m (minutes?), that makes a maximum of 576 requests per day. Anyway the problem fixed by itself at some point. I don't know why.

**Comment by gastonmorixe** [comment]
@eroldan yeah maybe they changed it, a few months ago it was ~140/day max. I was getting a few hours every day of that error. I guess if you use the App it counts towards it.
