### ISSUE TITLE
Retrieve sms

### ISSUE THREAD

**Issue by edwinrea** [gustavoqzdaa/ute_energy#5]
I am trying to install the component, but when I put my email and phone, I do not get the text message, I checked my data in the UTE portal and they are the same that I am putting in the fields.

I was checking the HA log and the following appears, maybe it is helpful

```
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'rocme.ute.com.uy'. It is strongly recommended to add certificate verification. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: An unverified HTTPS request is being made to host 'rocme.ute.com.uy'. It is strongly recommended to add certificate verification. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warn.warn(
```

**Comment by gustavoqzdaa** [comment]
That logs aren't related with the issue. You have to enable debug to verify the API response. Also verify the email inbox used, when you use an email different from the registered on UTE, a six-digit code is sent to that email.

```
logger:
  default: info
  logs:
    custom_components.ute_energy: debug
 ```

**Comment by edwinrea** [comment]
Thank you very much for the answer, I was able to enable the log, and I realized that the ute has another phone number registered, I was able to make the change and now it is configured correctly.
