### ISSUE TITLE
BUG: Not able to add ute_enegry integration to HA

### ISSUE THREAD

**Issue by krabbi** [gustavoqzdaa/ute_energy#6]
After install `ute_energy` component and trying to add this integration get next error:
```
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
```

First time loader spining and this meessage appears after ~30secs, next times this message appears immediately after select "UTE Energy" integration on "Add Integration" dialog.

I've tried install through HACS, and manually. Same result for both.

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2

**Comment by gustavoqzdaa** [comment]
Fixed in the last release
