### ISSUE TITLE
Problemas para integrarlo al dashboard de "energy"

### ISSUE THREAD

**Issue by euquiq** [gustavoqzdaa/ute_energy#8]
Hola! Recién instalé la última versión de Home Assistant y seguí los pasos para incorporar este brillante componente, que se ejecutaron sin problema y quedó instalado, aunque demoró bastante. Demoró sobre todo, luego de ingresar el pin que mandó UTE por SMS y darle OK a la dirección / cuenta de mi casa ... Al punto de que hasta sospecharía algún timeout (pero no mostró ningún error).

Cuando lo agrego como source al dashboard de Energy, me da el siguiente error:

`
Entity not defined
Check the integration or your configuration that provides:
sensor.ute
`
Nota: El Home Assistant está corriendo adentro de un container.  Por lo demás si bien el servicio de ute a veces parece medio intermitente, funciona ok!

![image](https://github.com/gustavoqzdaa/ute_energy/assets/31453004/682cd966-8ba9-4c23-b0dc-3f552b896957)

Cualquier ayuda se agradece y quedo atento para ver si puedo asistir en algo!
Enrique

**Comment by aronkahrs-us** [comment]
No tenes un componente que sea compatible, el dashboard de energia usa kWh basicamente, a la integración tenes que agregarle un sensor que te calcule el consumo(basicamente lo que te da el sensor Power por el tiempo de muestreo), ese sensor si lo podes integrar al dashboard.
Igual ojo, por experiencia eso no anda del todo bien, el consumo y el costo están muy lejos de lo real. Para solucionar eso lo que hice fue meterle un Utility meter diario a ese sensor nuevo que hay que crear, no lo he tenido un mes completo como para decirte que tan bien calcula ahora, pero pareciera ser mucho mas cercano a lo real
